version: '3.1'

services:

  db:
    image: postgres
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: d
      POSTGRES_PASSWORD: d

  adminer:
    image: adminer
    restart: always
    ports:
      - 1990:8080